# Generated by Django 5.1.7 on 2025-03-20 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KW', '0006_labour_age_labour_avatar_labour_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=15)),
                ('machine_name', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=255)),
                ('specification', models.TextField()),
                ('with_tractor', models.BooleanField(default=False)),
                ('tractor_company', models.CharField(blank=True, max_length=255, null=True)),
                ('tractor_model', models.CharField(blank=True, max_length=255, null=True)),
                ('hiring_cost_acre', models.IntegerField()),
                ('hiring_cost_hour', models.IntegerField()),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MachineAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_no', models.CharField(max_length=20)),
                ('ifsc', models.CharField(max_length=20)),
                ('machine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='KW.machine')),
            ],
        ),
        migrations.CreateModel(
            name='MachineImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='machin_images/')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='KW.machine')),
            ],
        ),
    ]
