# Generated by Django 5.1.7 on 2025-04-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KW', '0011_landrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sender Name')),
                ('sender_mobile', models.CharField(max_length=15, verbose_name='Sender Mobile Number')),
                ('hour', models.CharField(max_length=50, verbose_name='Hour')),
                ('period_start', models.DateField(verbose_name='Renting Period Start')),
                ('period_end', models.DateField(verbose_name='Renting Period End')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('village', models.CharField(max_length=100, verbose_name='Village')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='Status')),
                ('machine_id', models.IntegerField(verbose_name='Machine ID')),
                ('machine_name', models.CharField(max_length=100, verbose_name='Machine Name')),
                ('receiver_mobile', models.CharField(max_length=15, verbose_name='Receiver Mobile (Owner)')),
                ('request_date', models.CharField(max_length=20, verbose_name='Request Date')),
            ],
        ),
    ]
