# Generated by Django 5.1.7 on 2025-04-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KW', '0012_machinerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='landrequest',
            name='land_id',
            field=models.IntegerField(default=-1, verbose_name='Land ID'),
            preserve_default=False,
        ),
    ]
