# Generated by Django 5.1.7 on 2025-03-17 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KW', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='mobile',
        ),
    ]
