# Generated by Django 5.1.7 on 2025-03-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KW', '0002_rename_username_user_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('land_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('LandSize', models.IntegerField()),
                ('TotalRentPrice', models.IntegerField()),
                ('RentPricePerAcre', models.IntegerField()),
                ('rentPeriod', models.IntegerField()),
                ('irrigationSource', models.CharField(max_length=100)),
                ('extraFacilities', models.CharField(max_length=200)),
                ('AccName', models.CharField(max_length=50)),
                ('BankName', models.CharField(max_length=50)),
                ('AccNo', models.CharField(max_length=20)),
                ('IFSC', models.CharField(max_length=20)),
                ('map_location', models.CharField(max_length=20)),
            ],
        ),
    ]
