# Generated by Django 5.1.7 on 2025-03-18 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KW', '0003_land'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandPhotos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/')),
                ('land_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KW.land')),
            ],
        ),
    ]
