# Generated by Django 5.1.7 on 2025-03-19 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KW', '0004_landphotos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=15)),
                ('selected_state', models.CharField(max_length=100)),
                ('selected_district', models.CharField(max_length=100)),
                ('selected_village', models.CharField(max_length=100)),
                ('work_type', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_type', models.CharField(choices=[('Per Day', 'Per Day'), ('Per Hour', 'Per Hour')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LabourBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('b_account_no', models.CharField(max_length=50)),
                ('IFSC', models.CharField(max_length=20)),
                ('labour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='KW.labour')),
            ],
        ),
    ]
