# Generated by Django 5.1.7 on 2025-03-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KW', '0005_labour_labourbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='labour',
            name='avatar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labour',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='labour',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
