# Generated by Django 5.1.7 on 2025-03-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KW', '0007_machine_machineaccount_machineimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='district',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='state',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='village',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
