# Generated by Django 5.1.7 on 2025-04-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KW', '0009_alter_labour_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabourRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_mobile', models.CharField(max_length=15, verbose_name='Receiver Mobile Number')),
                ('name', models.CharField(max_length=100, verbose_name='Sender Name')),
                ('sender_mobile', models.CharField(max_length=15, verbose_name='Sender Mobile Number')),
                ('workTime', models.CharField(max_length=20, verbose_name='Work Time')),
                ('workUnit', models.CharField(max_length=10, verbose_name='Work Unit')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('village', models.CharField(max_length=100, verbose_name='Village')),
                ('workType', models.CharField(max_length=100, verbose_name='Work Type')),
                ('otherWork', models.CharField(blank=True, max_length=100, null=True, verbose_name='Other Work')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('period_start', models.DateField(verbose_name='Period Start')),
                ('period_end', models.DateField(verbose_name='Period End')),
                ('status', models.CharField(max_length=20, verbose_name='Status')),
                ('request_date', models.CharField(max_length=20, verbose_name='Request Date')),
            ],
        ),
    ]
