# Generated by Django 5.1.7 on 2025-04-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KW', '0010_labourrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sender Name')),
                ('sender_mobile', models.CharField(max_length=15, verbose_name='Sender Mobile Number')),
                ('landSize', models.CharField(max_length=50, verbose_name='Land Size')),
                ('period_start', models.DateField(verbose_name='Renting Period Start')),
                ('period_end', models.DateField(verbose_name='Renting Period End')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('receiver_mobile', models.CharField(max_length=15, verbose_name='Receiver Mobile Number')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='Status')),
                ('request_date', models.CharField(max_length=20, verbose_name='Request Date')),
            ],
        ),
    ]
