# Generated by Django 5.1.7 on 2025-04-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KW', '0013_landrequest_land_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='labourrequest',
            name='preview_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Preview Date'),
        ),
        migrations.AddField(
            model_name='labourrequest',
            name='preview_description',
            field=models.TextField(blank=True, null=True, verbose_name='Preview Description'),
        ),
        migrations.AddField(
            model_name='labourrequest',
            name='request_price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Request Price'),
        ),
        migrations.AddField(
            model_name='landrequest',
            name='preview_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Preview Date'),
        ),
        migrations.AddField(
            model_name='landrequest',
            name='preview_description',
            field=models.TextField(blank=True, null=True, verbose_name='Preview Description'),
        ),
        migrations.AddField(
            model_name='landrequest',
            name='request_price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Request Price'),
        ),
        migrations.AddField(
            model_name='machinerequest',
            name='preview_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Preview Date'),
        ),
        migrations.AddField(
            model_name='machinerequest',
            name='preview_description',
            field=models.TextField(blank=True, null=True, verbose_name='Preview Description'),
        ),
        migrations.AddField(
            model_name='machinerequest',
            name='request_price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Request Price'),
        ),
    ]
